let mock = [{
    id: 1,
    make: "Toyota",
    price: "$10,520.99",
    model: "Corolla",
    image: 'car1.jpg',
    status: "Used",
    color: "Blue",
    comments:[],
  },
  {
    id: 2,
    make: "Toyota",
    price: "$9,921.99",
    model: "Yaris",
    image: "car2.jpg",
    status: "Used",
    color: "Orange",
    comments:[],
  },
  {
    id: 3,
    make: "Toyota",
    price: "$19,201.99",
    model: "RAV4",
    image: 'car3.PNG',
    status: "New",
    color: "Green",
    comments:[],
  },
  {
    id: 4,
    make: "Toyota",
    price: "$15,499.99",
    model: "Camry",
    image: 'car4.PNG',
    status: "New",
    color: "Blue",
    comments:[],
  },
  {
    id: 5,
    make: "Toyota",
    price: "$22,499.99",
    model: "Supra",
    image: 'car5.PNG',
    status: "Used",
    color: "Red",
    comments:[],
  },
  {
    id: 6,
    make: "Volkswagen",
    price: "$12,000.00",
    model: "Golf",
    image: 'car1.jpg',
    status: "New",
    color: "Orange",
    comments:[],
  },
  {
    id: 7,
    make: "Volkswagen",
    price: "$13,499.99",
    model: "Jetta",
    image: 'car2.jpg',
    status: "Used",
    color: "Green",
    comments:[],
  },
  {
    id: 8,
    make: "BMW",
    price: "$17,349.99",
    model: "M3",
    image: 'car3.PNG',
    status: "Used",
    color: "Green",
    comments:[],
  },
  {
    id: 9,
    make: "Ford",
    price: "$10,249.99",
    model: "Focus",
    image: 'car4.PNG',
    status: "New",
    color: "Black",
    comments:[],
  },
  {
    id: 10,
    make: "Ford",
    price: "$20,499.99",
    model: "Bronco",
    image: 'car5.PNG',
    status: "New",
    color: "Gray",
    comments:[],
  },
]

export default mock;
